SiteLoja/Controllers/CategoriaController.cs
using SiteLoja.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteLoja.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        [HttpGet]
        public ActionResult List()
        {
            var categorias = new LojaRoupasEntities2().Categorias.ToList();
            return View(categorias);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            //estancia a classe do banco
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var categoria = banco.Categorias
                .Where(x => x.ID == id).SingleOrDefault();

            return View(categoria);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            var categoria = banco.Categorias
                .Where(x => x.ID == id).SingleOrDefault();

            banco.Categorias.Remove(categoria);
            banco.SaveChanges();

            return RedirectToAction("List");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Categoria categoria)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            banco.Categorias.Add(categoria);

            banco.SaveChanges();

            return RedirectToAction("Details", new { id = categoria.ID });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var categoria = banco.Categorias.Where(
                w => w.ID == id).SingleOrDefault();

            return View(categoria);
        }

        [HttpPost]
        public ActionResult Edit(Categoria categoria)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var categoriaNoBanco = banco.Categorias.Where(
                w => w.ID == categoria.ID).SingleOrDefault();

            categoriaNoBanco.Nome = categoria.Nome;

            banco.SaveChanges();

            return RedirectToAction("Details", new { id = categoria.ID });
        }


     }   

}

SiteLoja/Controllers/ProdutoController.cs
using SiteLoja.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteLoja.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult List()
        {
            ViewData["Titulo"] = "Todas as Roupas";
            ViewData["Data"] = DateTime.Now;

            var produtos = new LojaRoupasEntities2().Produtos.ToList();
            var totalprodutos = produtos.Count();

            ViewBag.Total = "Total de Produtos :";
            ViewBag.TotalProdutos = totalprodutos;


            return View(produtos);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var produto = banco.Produtos
                .Where(x => x.ID == id).SingleOrDefault();

            return View(produto);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            var produto = banco.Produtos
                .Where(x => x.ID == id).SingleOrDefault();

            banco.Produtos.Remove(produto);

            banco.SaveChanges();

            return RedirectToAction("List");
        }
        [HttpGet]
        public ActionResult Create()
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            var produto = banco.Produtos.ToList();
            var lista = new List<SelectListItem>();
            foreach (var pro in produto)
            {
                lista.Add(new SelectListItem
                {
                    Value = pro.ID.ToString(),
                    Text = pro.Nome
                });
            }

            ViewBag.IDProduto = lista;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Produto produto)
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            banco.Produtos.Add(produto);

            banco.SaveChanges();

            return RedirectToAction("Details", new { id = produto.ID });
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var produto = banco.Produtos.Where(
                w => w.ID == id).SingleOrDefault();

            var produtos = banco.Produtos.ToList();
            var lista = new List<SelectListItem>();
            foreach (var pro in produtos)
            {
                lista.Add(new SelectListItem
                {
                    Value = pro.ID.ToString(),
                    Text = pro.Nome,
                });
            }

            ViewBag.IDProduto = lista;

            return View(produto);
        }

        [HttpPost]
        public ActionResult Edit(Produto produto)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var produtoNoBanco = banco.Produtos.Where(
                w => w.ID == produto.ID).SingleOrDefault();

            //altera os dados para o que veio 

            produtoNoBanco.IDCategoia=produto.IDCategoia;   
            produtoNoBanco.Nome = produto.Nome;
            produtoNoBanco.Descricao = produto.Descricao;
            produtoNoBanco.Preco= produto.Preco;
            produtoNoBanco.PrecoAtual= produto.PrecoAtual;
            produtoNoBanco.ImagemUrl = produto.ImagemUrl;
            produtoNoBanco.ImagemThumbnaiUrl = produto.ImagemThumbnaiUrl;
            produtoNoBanco.RoupaDaSemana = produto.RoupaDaSemana;
            produtoNoBanco.EmEstoque = produto.EmEstoque;  
   

            banco.SaveChanges();

            return RedirectToAction("Details", new { id = produto.ID });
        }
    }
}

SiteLoja/Controllers/UsuarioController.cs
using SiteLoja.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SiteLoja.Controllers
{
    public class UsuarioController : Controller
    {
        [HttpGet]
        public ActionResult Details(int id)
        {

            LojaRoupasEntities2 banco = new LojaRoupasEntities2();

            var usuario = banco.Usuarios
                .Where(x => x.ID == id).SingleOrDefault();

            return View(usuario);
        }
        [HttpGet]
        public ActionResult Create()
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            var usuario = banco.Usuarios.ToList();
            var lista = new List<SelectListItem>();
            foreach (var pro in usuario)
            {
                lista.Add(new SelectListItem
                {
                    Value = pro.ID.ToString(),
                    Text = pro.Nome
                });
            }

            ViewBag.IDUsuario = lista;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Usuario usuario)
        {
            LojaRoupasEntities2 banco = new LojaRoupasEntities2();
            banco.Usuarios.Add(usuario);

            banco.SaveChanges();

            return RedirectToAction("Details", new { id = usuario.ID });
        }
    }
}

SiteLoja/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Moda Feminina- Jéssica Soler Souza</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/Images/Logotipo moda feminina preto e bege.png" alt="Logo da Loja de Roupas" class="img-fluid" style="max-height: 30px;" />
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Produtos", "List", "Produto", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Categorias", "List", "Categoria", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Usuário", "create", "Usuario", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>*@

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                <img src="~/Images/Logotipo moda feminina preto e bege.png" alt="Logo da Loja de Roupas" class="img-fluid" style="max-height: 30px;" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Produtos", "List", "Produto", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Categorias", "List", "Categoria", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Login", "Index", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Usuario", "Create", "Usuario", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        @*<a class="nav-link dropdown-toggle" href="#" id="usuarioDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Usuário
                        </a>*@
                        <div class="dropdown-menu" aria-labelledby="usuarioDropdown">
                            <a class="dropdown-item" href="#">Login</a>
                            <a class="dropdown-item" href="#">Cadastrar</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET - Jéssica Soler Souza</p>
        </footer>
    </div>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SiteLoja/Views/Shared/_ProdutosResumo.cshtml
@model SiteLoja.Models.Produto

<div class=" col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid" /></p>
    <h4>@Model.Nome</h4>
    <h3>Preço: @Model.Preco.ToString("c")</h3>
    <p>@Model.DescricaoCurta</p>
</div>